version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${VOLUME_NAME}:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - ${NETWORK_NAME}

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge